// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 51zBY4D7hL5NMVRD6FEcWe
// Component: IIM_6PM7I3

import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Lo from "../../Lo"; // plasmic-import: 1BOwkZ1j0D/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_website_starter.module.css"; // plasmic-import: 51zBY4D7hL5NMVRD6FEcWe/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: IIM_6PM7I3/css

import StrategySvgrepoComsvgIcon from "./icons/PlasmicIcon__StrategySvgrepoComsvg"; // plasmic-import: _SHtgJLA3F/icon
import FigureheadSvgrepoComsvgIcon from "./icons/PlasmicIcon__FigureheadSvgrepoComsvg"; // plasmic-import: Evk-5z9Avh/icon
import AwardBadgePrizeRewardRibbonSvgrepoComsvgIcon from "./icons/PlasmicIcon__AwardBadgePrizeRewardRibbonSvgrepoComsvg"; // plasmic-import: mFxIqTEc17/icon
import UnitarianUniversalismSvgrepoComsvgIcon from "./icons/PlasmicIcon__UnitarianUniversalismSvgrepoComsvg"; // plasmic-import: akyxwmcyu5/icon
import DotIcon from "./icons/PlasmicIcon__Dot"; // plasmic-import: CkYkMkc0f/icon
import Rectangle31Icon from "./icons/PlasmicIcon__Rectangle31"; // plasmic-import: P8yNT8AsaD/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: bRZrhPo21M/icon
import Group2Icon from "./icons/PlasmicIcon__Group2"; // plasmic-import: vvn2oZBzGi/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: O7aW-q5bhr/icon
import Group3Icon from "./icons/PlasmicIcon__Group3"; // plasmic-import: Qz70YqNP-c/icon
import weblogo1PngEbsUsOfE3 from "./images/weblogo1Png.png"; // plasmic-import: EbsUSOfE3/picture
import dotOrnamentpngTPnlguW4 from "./images/dotOrnamentpng.png"; // plasmic-import: -tPnlguW4/picture
import group751Png935L3KBff from "./images/group751Png.png"; // plasmic-import: 935L3kBff/picture
import rectangle33PngQxuhhJ2D from "./images/rectangle33Png.png"; // plasmic-import: QXUHH_j2d/picture
import rectangle36PngB3IkWnjr1 from "./images/rectangle36Png.png"; // plasmic-import: B3ikWNJR1/picture
import rectangle34PngRNGk8Y4DC from "./images/rectangle34Png.png"; // plasmic-import: rNGk8y4dC/picture
import rectangle35PngWNxarmUxH from "./images/rectangle35Png.png"; // plasmic-import: wNxarmUxH/picture
import group80PngESkS856Ir from "./images/group80Png.png"; // plasmic-import: eSkS856ir/picture
import groupVdKikHq4 from "./images/group.svg"; // plasmic-import: Vd_kikHQ4/picture

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  lo?: p.Flex<typeof Lo>;
  link?: p.Flex<"a">;
  whatLaVerneBringsToTheTable?: p.Flex<"div">;
  experienceInsightAndAProvenTrackRecordForSuccess?: p.Flex<"div">;
  rectangle25?: p.Flex<"div">;
  group78?: p.Flex<"div">;
  group65?: p.Flex<"div">;
  rectangle27?: p.Flex<"div">;
  rectangle28?: p.Flex<"div">;
  unparalleledInsightsForMarketExpansion?: p.Flex<"div">;
  group67?: p.Flex<"div">;
  rectangle29?: p.Flex<"div">;
  rectangle30?: p.Flex<"div">;
  elevateLeadershipSkillsAndCultivateTeamExcellence?: p.Flex<"div">;
  group69?: p.Flex<"div">;
  rectangle31?: p.Flex<"div">;
  rectangle32?: p.Flex<"div">;
  group66?: p.Flex<"div">;
  rectangle33?: p.Flex<"div">;
  rectangle34?: p.Flex<"div">;
  actionableStrategiesForDiverseInclusiveWorkplaces?: p.Flex<"div">;
  group79?: p.Flex<"div">;
  rectangle26?: p.Flex<"div">;
  group70?: p.Flex<"div">;
  chartingTheCourseForSuccess?: p.Flex<"div">;
  newsletter?: p.Flex<"div">;
  group73?: p.Flex<"div">;
  rectangle35?: p.Flex<"div">;
  rectangle36?: p.Flex<"div">;
  group74?: p.Flex<"div">;
  frame3?: p.Flex<"div">;
  empoweringInsightsFromARenownedBusinessStrategistSpeaker?: p.Flex<"div">;
  group81?: p.Flex<"div">;
  facebook?: p.Flex<"div">;
  twitter?: p.Flex<"div">;
  group?: p.Flex<"div">;
  linkedin?: p.Flex<"div">;
  group2?: p.Flex<"div">;
};

export interface DefaultHomepageProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__lzNLx)}>
            <div className={classNames(projectcss.all, sty.columns__cnipl)}>
              <div className={classNames(projectcss.all, sty.column__taki6)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___0C3Kc)}
                  displayHeight={"71px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: weblogo1PngEbsUsOfE3,
                    fullWidth: 154,
                    fullHeight: 100,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column___98RP)} />
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__g8RyC)}>
            <div className={classNames(projectcss.all, sty.columns__sIgdL)}>
              <div className={classNames(projectcss.all, sty.column__cw1BJ)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zjku0
                  )}
                >
                  {"Ignite Your Event \nWith LaVerne Daley"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__z0LTg
                  )}
                >
                  {
                    "Empowering Insights from a Renowned Business Strategist & Speaker"
                  }
                </div>
                <Lo
                  data-plasmic-name={"lo"}
                  data-plasmic-override={overrides.lo}
                  className={classNames("__wab_instance", sty.lo)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vhTfk
                  )}
                >
                  {
                    "Laverne's minimum asking price is $5,000 thanks for your time and co-operation."
                  }
                </div>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__xabMt)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: dotOrnamentpngTPnlguW4,
                    fullWidth: 404,
                    fullHeight: 154,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__r6Zyr)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__dq0SL)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"424px" as const}
                  loading={"lazy" as const}
                  src={{
                    src: group751Png935L3KBff,
                    fullWidth: 817,
                    fullHeight: 608,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___8HAiu)}>
            <div className={classNames(projectcss.all, sty.columns__b1NsF)}>
              <div className={classNames(projectcss.all, sty.column__ubwGc)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tk8Ou
                  )}
                >
                  {"Spoken At:"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__c1222
                  )}
                >
                  {
                    "Transforming platforms with insightful dialogue at top global forums."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__wnDa)}>
                <div className={classNames(projectcss.all, sty.columns__xIoT4)}>
                  <div
                    className={classNames(projectcss.all, sty.column___1Uy5B)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__i6ByF)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"120px" as const}
                      loading={"lazy" as const}
                      src={{
                        src: rectangle33PngQxuhhJ2D,
                        fullWidth: 184,
                        fullHeight: 136,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__he7Yr)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__py0D0)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"136px" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"120px" as const}
                      loading={"lazy" as const}
                      src={{
                        src: rectangle36PngB3IkWnjr1,
                        fullWidth: 184,
                        fullHeight: 136,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column___7NbUu)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__t7Bg)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"136px" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"120px" as const}
                      loading={"lazy" as const}
                      src={{
                        src: rectangle34PngRNGk8Y4DC,
                        fullWidth: 184,
                        fullHeight: 136,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column___54Ll7)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__wzR39)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"136px" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"120px" as const}
                      loading={"lazy" as const}
                      src={{
                        src: rectangle35PngWNxarmUxH,
                        fullWidth: 184,
                        fullHeight: 136,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>
                <a
                  data-plasmic-name={"link"}
                  data-plasmic-override={overrides.link}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link
                  )}
                  href={"https://lavernedaley.com/" as const}
                  target={"_blank" as const}
                >
                  {"Click here to see more events"}
                </a>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__xjiAu)}>
            <div className={classNames(projectcss.all, sty.columns__dmfa9)}>
              <div className={classNames(projectcss.all, sty.column__fauf8)}>
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__lj92)}
                  direction={"up" as const}
                  triggerOnce={true}
                >
                  <div
                    data-plasmic-name={"whatLaVerneBringsToTheTable"}
                    data-plasmic-override={
                      overrides.whatLaVerneBringsToTheTable
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.whatLaVerneBringsToTheTable
                    )}
                  >
                    {"What LaVerne Brings to the Table\n"}
                  </div>
                </Reveal>
                <div
                  data-plasmic-name={
                    "experienceInsightAndAProvenTrackRecordForSuccess"
                  }
                  data-plasmic-override={
                    overrides.experienceInsightAndAProvenTrackRecordForSuccess
                  }
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.experienceInsightAndAProvenTrackRecordForSuccess
                  )}
                >
                  {
                    "Experience, Insight, and a Proven Track Record \nfor Success\n"
                  }
                </div>
                <div
                  data-plasmic-name={"rectangle25"}
                  data-plasmic-override={overrides.rectangle25}
                  className={classNames(projectcss.all, sty.rectangle25)}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__mJg3M)}>
                <div className={classNames(projectcss.all, sty.columns__ch7Nv)}>
                  <div
                    className={classNames(projectcss.all, sty.column__phFhj)}
                  >
                    <div
                      data-plasmic-name={"group78"}
                      data-plasmic-override={overrides.group78}
                      className={classNames(projectcss.all, sty.group78)}
                    >
                      <Reveal
                        className={classNames(
                          "__wab_instance",
                          sty.reveal__blQSo
                        )}
                        direction={"left" as const}
                        duration={2000 as const}
                        triggerOnce={true}
                      >
                        <div
                          data-plasmic-name={"group65"}
                          data-plasmic-override={overrides.group65}
                          className={classNames(projectcss.all, sty.group65)}
                        >
                          <div
                            data-plasmic-name={"rectangle27"}
                            data-plasmic-override={overrides.rectangle27}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle27
                            )}
                          />

                          <div
                            data-plasmic-name={"rectangle28"}
                            data-plasmic-override={overrides.rectangle28}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle28
                            )}
                          >
                            <StrategySvgrepoComsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__xPTmV
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            data-plasmic-name={
                              "unparalleledInsightsForMarketExpansion"
                            }
                            data-plasmic-override={
                              overrides.unparalleledInsightsForMarketExpansion
                            }
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.unparalleledInsightsForMarketExpansion
                            )}
                          >
                            {"Unparalleled insights for  \nmarket expansion.\n"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__hfcDv
                            )}
                          >
                            {"Strategic Expertise"}
                          </div>
                        </div>
                      </Reveal>
                      <Reveal
                        className={classNames(
                          "__wab_instance",
                          sty.reveal___0KYpe
                        )}
                        direction={"top-left" as const}
                        triggerOnce={true}
                      >
                        <div
                          data-plasmic-name={"group67"}
                          data-plasmic-override={overrides.group67}
                          className={classNames(projectcss.all, sty.group67)}
                        >
                          <div
                            data-plasmic-name={"rectangle29"}
                            data-plasmic-override={overrides.rectangle29}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle29
                            )}
                          />

                          <div
                            data-plasmic-name={"rectangle30"}
                            data-plasmic-override={overrides.rectangle30}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle30
                            )}
                          >
                            <FigureheadSvgrepoComsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg___2DWn8
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            data-plasmic-name={
                              "elevateLeadershipSkillsAndCultivateTeamExcellence"
                            }
                            data-plasmic-override={
                              overrides.elevateLeadershipSkillsAndCultivateTeamExcellence
                            }
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.elevateLeadershipSkillsAndCultivateTeamExcellence
                            )}
                          >
                            {
                              "Elevate leadership skills and cultivate team excellence.\n"
                            }
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__yYo6M
                            )}
                          >
                            {"Leadership Development"}
                          </div>
                        </div>
                      </Reveal>
                      <Reveal
                        className={classNames(
                          "__wab_instance",
                          sty.reveal__zI8Q8
                        )}
                        direction={"top-left" as const}
                        triggerOnce={true}
                      >
                        <div
                          data-plasmic-name={"group69"}
                          data-plasmic-override={overrides.group69}
                          className={classNames(projectcss.all, sty.group69)}
                        >
                          <div
                            data-plasmic-name={"rectangle31"}
                            data-plasmic-override={overrides.rectangle31}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle31
                            )}
                          />

                          <div
                            data-plasmic-name={"rectangle32"}
                            data-plasmic-override={overrides.rectangle32}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle32
                            )}
                          >
                            <AwardBadgePrizeRewardRibbonSvgrepoComsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__ayba
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___6ZlHm
                            )}
                          >
                            {
                              "Inspiration from one of South Florida's most influential leaders."
                            }
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___0IgmZ
                            )}
                          >
                            {"Award-Winning Success"}
                          </div>
                        </div>
                      </Reveal>
                      <Reveal
                        className={classNames(
                          "__wab_instance",
                          sty.reveal__uXbLo
                        )}
                        direction={"top-left" as const}
                        triggerOnce={true}
                      >
                        <div
                          data-plasmic-name={"group66"}
                          data-plasmic-override={overrides.group66}
                          className={classNames(projectcss.all, sty.group66)}
                        >
                          <div
                            data-plasmic-name={"rectangle33"}
                            data-plasmic-override={overrides.rectangle33}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle33
                            )}
                          />

                          <div
                            data-plasmic-name={"rectangle34"}
                            data-plasmic-override={overrides.rectangle34}
                            className={classNames(
                              projectcss.all,
                              sty.rectangle34
                            )}
                          >
                            <UnitarianUniversalismSvgrepoComsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__wetRw
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            data-plasmic-name={
                              "actionableStrategiesForDiverseInclusiveWorkplaces"
                            }
                            data-plasmic-override={
                              overrides.actionableStrategiesForDiverseInclusiveWorkplaces
                            }
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.actionableStrategiesForDiverseInclusiveWorkplaces
                            )}
                          >
                            {
                              "Actionable strategies for diverse, inclusive workplaces.\n"
                            }
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___4LTc
                            )}
                          >
                            {"Diversity & Inclusion Advocacy"}
                          </div>
                        </div>
                      </Reveal>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__khzWi)}>
            <div className={classNames(projectcss.all, sty.columns__dp15V)}>
              <div className={classNames(projectcss.all, sty.column__bjdEu)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___7O6HS)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: group80PngESkS856Ir,
                    fullWidth: 650,
                    fullHeight: 472,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__nMps1)}>
                <div
                  data-plasmic-name={"group79"}
                  data-plasmic-override={overrides.group79}
                  className={classNames(projectcss.all, sty.group79)}
                >
                  <div
                    data-plasmic-name={"rectangle26"}
                    data-plasmic-override={overrides.rectangle26}
                    className={classNames(projectcss.all, sty.rectangle26)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nfHVo
                    )}
                  >
                    {
                      "LaVerne Daley's exceptional expertise and leadership skills ignite potential and fuel success. Embrace strategic thinking and embark on an inspiring journey of organizational transformation."
                    }
                  </div>
                  <div
                    data-plasmic-name={"group70"}
                    data-plasmic-override={overrides.group70}
                    className={classNames(projectcss.all, sty.group70)}
                  >
                    <div
                      data-plasmic-name={"chartingTheCourseForSuccess"}
                      data-plasmic-override={
                        overrides.chartingTheCourseForSuccess
                      }
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.chartingTheCourseForSuccess
                      )}
                    >
                      {"Charting the Course \nfor Success\n"}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___7XNuz)}>
            <div className={classNames(projectcss.all, sty.columns__voRjm)}>
              <div className={classNames(projectcss.all, sty.column___4CDNh)}>
                <div
                  data-plasmic-name={"newsletter"}
                  data-plasmic-override={overrides.newsletter}
                  className={classNames(projectcss.all, sty.newsletter)}
                >
                  <div
                    data-plasmic-name={"group73"}
                    data-plasmic-override={overrides.group73}
                    className={classNames(projectcss.all, sty.group73)}
                  >
                    <DotIcon
                      className={classNames(projectcss.all, sty.svg__rrIiv)}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"rectangle35"}
                    data-plasmic-override={overrides.rectangle35}
                    className={classNames(projectcss.all, sty.rectangle35)}
                  />

                  <div
                    data-plasmic-name={"rectangle36"}
                    data-plasmic-override={overrides.rectangle36}
                    className={classNames(projectcss.all, sty.rectangle36)}
                  />

                  <Rectangle31Icon
                    className={classNames(projectcss.all, sty.svg__bBdmd)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"group74"}
                    data-plasmic-override={overrides.group74}
                    className={classNames(projectcss.all, sty.group74)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"frame3"}
                      data-plasmic-override={overrides.frame3}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lMfM
                        )}
                      >
                        {"Book Laverne"}
                      </div>
                    </p.Stack>
                  </div>
                  <div
                    data-plasmic-name={
                      "empoweringInsightsFromARenownedBusinessStrategistSpeaker"
                    }
                    data-plasmic-override={
                      overrides.empoweringInsightsFromARenownedBusinessStrategistSpeaker
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.empoweringInsightsFromARenownedBusinessStrategistSpeaker
                    )}
                  >
                    {
                      "Empowering Insights from a Renowned Business Strategist & Speaker\n"
                    }
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uxY4H
                    )}
                  >
                    {"Book Laverne Today"}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__zxJ8U)}>
            <div className={classNames(projectcss.all, sty.columns__srC9R)}>
              <div className={classNames(projectcss.all, sty.column__omlG5)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___8Wqm2)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: weblogo1PngEbsUsOfE3,
                    fullWidth: 154,
                    fullHeight: 100,
                    aspectRatio: undefined
                  }}
                />

                <div
                  data-plasmic-name={"group81"}
                  data-plasmic-override={overrides.group81}
                  className={classNames(projectcss.all, sty.group81)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__elmU0
                    )}
                  >
                    {"About Laverne"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__u1P0J
                    )}
                  >
                    {
                      "LaVerne Daley, is  a renowned business strategist and speaker. Her strategic insights, coupled with her commitment to leadership development and diversity, inspire and transform audiences at top global forums and conferences."
                    }
                  </div>
                  <div
                    data-plasmic-name={"facebook"}
                    data-plasmic-override={overrides.facebook}
                    className={classNames(projectcss.all, sty.facebook)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__gDlYt)}
                      displayHeight={"36px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"36px" as const}
                      loading={"lazy" as const}
                      src={{
                        src: groupVdKikHq4,
                        fullWidth: 36,
                        fullHeight: 36,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                  <div
                    data-plasmic-name={"twitter"}
                    data-plasmic-override={overrides.twitter}
                    className={classNames(projectcss.all, sty.twitter)}
                  >
                    <div
                      data-plasmic-name={"group"}
                      data-plasmic-override={overrides.group}
                      className={classNames(projectcss.all, sty.group)}
                    >
                      <VectorIcon
                        className={classNames(projectcss.all, sty.svg__v5Atk)}
                        role={"img"}
                      />

                      <Group2Icon
                        className={classNames(projectcss.all, sty.svg__kiELy)}
                        role={"img"}
                      />
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"linkedin"}
                    data-plasmic-override={overrides.linkedin}
                    className={classNames(projectcss.all, sty.linkedin)}
                  >
                    <div
                      data-plasmic-name={"group2"}
                      data-plasmic-override={overrides.group2}
                      className={classNames(projectcss.all, sty.group2)}
                    >
                      <Vector2Icon
                        className={classNames(projectcss.all, sty.svg__eFcQo)}
                        role={"img"}
                      />

                      <Group3Icon
                        className={classNames(projectcss.all, sty.svg__tVpV)}
                        role={"img"}
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__s9Wp6)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aRq1X
                  )}
                >
                  {"Useful Links"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__x0NVg
                  )}
                >
                  {"Book Laverne"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__a2EWc
                  )}
                >
                  {"About"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__onpN5
                  )}
                >
                  {"Contact Lglobal"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___8MGtL)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ixOtj
                  )}
                >
                  {"Global Network"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jhRxR
                  )}
                >
                  {"World Impact"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4GDr
                  )}
                >
                  {"Partners"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__llh0M)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wj6R9
                  )}
                >
                  {"Services"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kEl6W
                  )}
                >
                  {"Consulting"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vnjJb
                  )}
                >
                  {"Partners"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___4Pswb)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__v26Eq
                  )}
                >
                  {"Contact"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8MSt8
                  )}
                >
                  {"Consulting"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yXDS
                  )}
                >
                  {"Partners"}
                </div>
              </div>
            </div>
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__cV7DN
            )}
          >
            {"Copyright \u00a9 2023 Laverne Daley . Web Design by JD"}
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "lo",
    "link",
    "whatLaVerneBringsToTheTable",
    "experienceInsightAndAProvenTrackRecordForSuccess",
    "rectangle25",
    "group78",
    "group65",
    "rectangle27",
    "rectangle28",
    "unparalleledInsightsForMarketExpansion",
    "group67",
    "rectangle29",
    "rectangle30",
    "elevateLeadershipSkillsAndCultivateTeamExcellence",
    "group69",
    "rectangle31",
    "rectangle32",
    "group66",
    "rectangle33",
    "rectangle34",
    "actionableStrategiesForDiverseInclusiveWorkplaces",
    "group79",
    "rectangle26",
    "group70",
    "chartingTheCourseForSuccess",
    "newsletter",
    "group73",
    "rectangle35",
    "rectangle36",
    "group74",
    "frame3",
    "empoweringInsightsFromARenownedBusinessStrategistSpeaker",
    "group81",
    "facebook",
    "twitter",
    "group",
    "linkedin",
    "group2"
  ],
  lo: ["lo"],
  link: ["link"],
  whatLaVerneBringsToTheTable: ["whatLaVerneBringsToTheTable"],
  experienceInsightAndAProvenTrackRecordForSuccess: [
    "experienceInsightAndAProvenTrackRecordForSuccess"
  ],
  rectangle25: ["rectangle25"],
  group78: [
    "group78",
    "group65",
    "rectangle27",
    "rectangle28",
    "unparalleledInsightsForMarketExpansion",
    "group67",
    "rectangle29",
    "rectangle30",
    "elevateLeadershipSkillsAndCultivateTeamExcellence",
    "group69",
    "rectangle31",
    "rectangle32",
    "group66",
    "rectangle33",
    "rectangle34",
    "actionableStrategiesForDiverseInclusiveWorkplaces"
  ],
  group65: [
    "group65",
    "rectangle27",
    "rectangle28",
    "unparalleledInsightsForMarketExpansion"
  ],
  rectangle27: ["rectangle27"],
  rectangle28: ["rectangle28"],
  unparalleledInsightsForMarketExpansion: [
    "unparalleledInsightsForMarketExpansion"
  ],
  group67: [
    "group67",
    "rectangle29",
    "rectangle30",
    "elevateLeadershipSkillsAndCultivateTeamExcellence"
  ],
  rectangle29: ["rectangle29"],
  rectangle30: ["rectangle30"],
  elevateLeadershipSkillsAndCultivateTeamExcellence: [
    "elevateLeadershipSkillsAndCultivateTeamExcellence"
  ],
  group69: ["group69", "rectangle31", "rectangle32"],
  rectangle31: ["rectangle31"],
  rectangle32: ["rectangle32"],
  group66: [
    "group66",
    "rectangle33",
    "rectangle34",
    "actionableStrategiesForDiverseInclusiveWorkplaces"
  ],
  rectangle33: ["rectangle33"],
  rectangle34: ["rectangle34"],
  actionableStrategiesForDiverseInclusiveWorkplaces: [
    "actionableStrategiesForDiverseInclusiveWorkplaces"
  ],
  group79: ["group79", "rectangle26", "group70", "chartingTheCourseForSuccess"],
  rectangle26: ["rectangle26"],
  group70: ["group70", "chartingTheCourseForSuccess"],
  chartingTheCourseForSuccess: ["chartingTheCourseForSuccess"],
  newsletter: [
    "newsletter",
    "group73",
    "rectangle35",
    "rectangle36",
    "group74",
    "frame3",
    "empoweringInsightsFromARenownedBusinessStrategistSpeaker"
  ],
  group73: ["group73"],
  rectangle35: ["rectangle35"],
  rectangle36: ["rectangle36"],
  group74: ["group74", "frame3"],
  frame3: ["frame3"],
  empoweringInsightsFromARenownedBusinessStrategistSpeaker: [
    "empoweringInsightsFromARenownedBusinessStrategistSpeaker"
  ],
  group81: ["group81", "facebook", "twitter", "group", "linkedin", "group2"],
  facebook: ["facebook"],
  twitter: ["twitter", "group"],
  group: ["group"],
  linkedin: ["linkedin", "group2"],
  group2: ["group2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  lo: typeof Lo;
  link: "a";
  whatLaVerneBringsToTheTable: "div";
  experienceInsightAndAProvenTrackRecordForSuccess: "div";
  rectangle25: "div";
  group78: "div";
  group65: "div";
  rectangle27: "div";
  rectangle28: "div";
  unparalleledInsightsForMarketExpansion: "div";
  group67: "div";
  rectangle29: "div";
  rectangle30: "div";
  elevateLeadershipSkillsAndCultivateTeamExcellence: "div";
  group69: "div";
  rectangle31: "div";
  rectangle32: "div";
  group66: "div";
  rectangle33: "div";
  rectangle34: "div";
  actionableStrategiesForDiverseInclusiveWorkplaces: "div";
  group79: "div";
  rectangle26: "div";
  group70: "div";
  chartingTheCourseForSuccess: "div";
  newsletter: "div";
  group73: "div";
  rectangle35: "div";
  rectangle36: "div";
  group74: "div";
  frame3: "div";
  empoweringInsightsFromARenownedBusinessStrategistSpeaker: "div";
  group81: "div";
  facebook: "div";
  twitter: "div";
  group: "div";
  linkedin: "div";
  group2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    lo: makeNodeComponent("lo"),
    link: makeNodeComponent("link"),
    whatLaVerneBringsToTheTable: makeNodeComponent(
      "whatLaVerneBringsToTheTable"
    ),
    experienceInsightAndAProvenTrackRecordForSuccess: makeNodeComponent(
      "experienceInsightAndAProvenTrackRecordForSuccess"
    ),
    rectangle25: makeNodeComponent("rectangle25"),
    group78: makeNodeComponent("group78"),
    group65: makeNodeComponent("group65"),
    rectangle27: makeNodeComponent("rectangle27"),
    rectangle28: makeNodeComponent("rectangle28"),
    unparalleledInsightsForMarketExpansion: makeNodeComponent(
      "unparalleledInsightsForMarketExpansion"
    ),
    group67: makeNodeComponent("group67"),
    rectangle29: makeNodeComponent("rectangle29"),
    rectangle30: makeNodeComponent("rectangle30"),
    elevateLeadershipSkillsAndCultivateTeamExcellence: makeNodeComponent(
      "elevateLeadershipSkillsAndCultivateTeamExcellence"
    ),
    group69: makeNodeComponent("group69"),
    rectangle31: makeNodeComponent("rectangle31"),
    rectangle32: makeNodeComponent("rectangle32"),
    group66: makeNodeComponent("group66"),
    rectangle33: makeNodeComponent("rectangle33"),
    rectangle34: makeNodeComponent("rectangle34"),
    actionableStrategiesForDiverseInclusiveWorkplaces: makeNodeComponent(
      "actionableStrategiesForDiverseInclusiveWorkplaces"
    ),
    group79: makeNodeComponent("group79"),
    rectangle26: makeNodeComponent("rectangle26"),
    group70: makeNodeComponent("group70"),
    chartingTheCourseForSuccess: makeNodeComponent(
      "chartingTheCourseForSuccess"
    ),
    newsletter: makeNodeComponent("newsletter"),
    group73: makeNodeComponent("group73"),
    rectangle35: makeNodeComponent("rectangle35"),
    rectangle36: makeNodeComponent("rectangle36"),
    group74: makeNodeComponent("group74"),
    frame3: makeNodeComponent("frame3"),
    empoweringInsightsFromARenownedBusinessStrategistSpeaker: makeNodeComponent(
      "empoweringInsightsFromARenownedBusinessStrategistSpeaker"
    ),
    group81: makeNodeComponent("group81"),
    facebook: makeNodeComponent("facebook"),
    twitter: makeNodeComponent("twitter"),
    group: makeNodeComponent("group"),
    linkedin: makeNodeComponent("linkedin"),
    group2: makeNodeComponent("group2"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
